---
- name: Install, configure, and start Apache on {{ ansible_distribution }}
  block:
    - name: Install Apache
      yum: name=httpd state=latest

    - name: Enable httpd.service
      service: name=httpd state=started enabled=yes

    - name: Create an index.html
      template: src=index.j2.html dest=/var/www/html/index.html owner=root group=root mode=0644
      notify:
        - reload httpd.service

    - name: Configure Firewall
      firewalld: port=80/tcp  permanent=yes state=enabled
      notify:
        - reload firewall
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install, configure FTP-server
  block:
    - name: Install vsftpd
      yum: name=vsftpd state=latest

