---
- name: reload firewall
  service: name=firewalld state=reloaded

- name: reconfigure grub
  command: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: reload httpd.service
  service: name=httpd.service state=reloaded