---
- name: Creating new users
  user:
    name: "{{ item.name }}"
    state: present
    password: "{{ item.password }}"
    comment: "{{ item.comment }}"
    home: "{{ item.home }}"
  loop: "{{ users }}"