---
- name: Creating user {{ item.name }}
  user: name="{{ item.name }}" state=present password="{{ item.passwords }}" comment="{{ item.comment }}" home="{{ item.home }}"
  with_together:
    - "{{ users }}"
    - "{{ passwords }}"


