---
- name: Creating users {{ users.value }}
  user:
    name: "{{ item[0].[1] }}"
    state: present
    create_home: yes
    password: "{{ item[1].[1] | password_hash('sha512') }}"
    comment: "{{ item[0].[1] }}@example.com"
    home: "/home/{{ item[0].[1] }}"
  with_together:
    - "{{ users }}"
    - "{{ passwords }}"
#
#- name: Creating user {{ users.user2 }}
#  user:
#    name: "{{ users.user2 }}"
#    state: present
#    create_home: yes
#    password: "{{ passwords.password2 | password_hash('sha512') }}"
#    comment: "{{ users.user2 }}@example.com"
#    home: "/home/{{ users.user2 }}"
#
#- name: Creating user {{ users.user3 }}
#  user:
#    name: "{{ users.user3 }}"
#    state: present
#    create_home: yes
#    password: "{{ passwords.password3 | password_hash('sha512') }}"
#    comment: "{{ users.user3 }}@example.com"
#    home: "/home/{{ users.user3 }}"