---
- name: Creating users {{ users }}
  user:
    name: "{{ item.0 }}"
    state: present
    create_home: yes
    password: "{{ item.1 | password_hash('sha512') }}"
    comment: "{{ item.0 }}@example.com"
    home: "/home/{{ item.0 }}"
    update_password: on_create
  with_together:
    - "{{ users }}"
    - "{{ passwords }}"
