---
- name: Creating new users
  user: name={{ users.name }} state=present comment="{{ users.name }}@example.com" create_home=yes home="/home/{{ users.name }}"

- name: Creating new users
  user: name={{ users.name }} state=absent