---
- name: Creating new users
  user: name={{ item }} state=present password={{ item }}.password comment="{{ item }}@example.com" create_home=yes home="/home/{{ item }}"
  with_items: ["Alice","Bob","Carol"]


