---
- name: Creating user {{ users.user1 }}
  user:
    name: "{{ users.user1 }}"
    state: present
    create_home: yes
    password: "{{ password1 | password_hash('sha512') }}"
    comment: "{{ users.user1 }}@example.com"
    home: "/home/{{ users.user1 }}"

- name: Creating user {{ users.user2 }}
  user:
    name: "{{ users.user2 }}"
    state: present
    create_home: yes
    password: "{{ password2 | password_hash('sha512') }}"
    comment: "{{ users.user2 }}@example.com"
    home: "/home/{{ users.user2 }}"

- name: Creating user {{ users.user3 }}
  user:
    name: "{{ users.user3 }}"
    state: present
    create_home: yes
    password: "{{ password3 | password_hash('sha512') }}"
    comment: "{{ users.user3 }}@example.com"
    home: "/home/{{ users.user3 }}"