---
- name: Creating new users
  user: name="{{ item.name }}" state=present password="{{ item.password }}" comment="{{ item.comment }}" create_home=yes home="{{ item.home }}"
  with_items: {{ users }}


