---
- name: Creating user {{ users.value }}
  user:
    name: "{{ users.value }}"
    state: present
    create_home: yes
    password: "{{ passwords.value | password_hash('sha512') }}"
    comment: "{{ users.value }}@example.com"
    home: "/home/{{ users.value }}"

#
#- name: Creating user {{ users.user2 }}
#  user:
#    name: "{{ users.user2 }}"
#    state: present
#    create_home: yes
#    password: "{{ passwords.password2 | password_hash('sha512') }}"
#    comment: "{{ users.user2 }}@example.com"
#    home: "/home/{{ users.user2 }}"
#
#- name: Creating user {{ users.user3 }}
#  user:
#    name: "{{ users.user3 }}"
#    state: present
#    create_home: yes
#    password: "{{ passwords.password3 | password_hash('sha512') }}"
#    comment: "{{ users.user3 }}@example.com"
#    home: "/home/{{ users.user3 }}"