---
- name: Install, configure, and start Apache
  block:
  - name: Install Apache Web-server
    yum: name=httpd state=latest

  - name: Enable httpd.service
    service: name=httpd state=started enabled=yes

  - name: Create an index.html
    template: src=index.j2.html dest=/var/www/html/index.html owner=root group=root mode=0644 
    notify:
      - reload httpd.service
  
  - name: Configure Firewall
    firewalld: port=80/tcp  permanent=yes state=enabled
    notify:
      - reload firewall
  tags:
    - install_apache

- name: Delete and disabled Apache Web-server
  block:
  - name: Remove Apache from a Web-server
    yum: name=httpd state=absent

  - name: Deleting a file
    file: path=/var/www/html/index.html state=absent

  - name: Firewalld
    firewalld:  port=80/tcp state=disabled permanent=yes
    notify:
      - reload firewall
  tags:
    - delete_apache

- name: Configure grub with new params
  block:
    - name: Check if params already in grub config
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX=".*(net.ifnames[=]\d+){1}'
        backup: yes
        state: absent
      check_mode: true
      register: grub_cmdline_check_netifnames
      changed_when: false

    - name: Check if params already in grub config
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX=".*(biosdevname[=]\d+){1}'
        backup: yes
        state: absent
      check_mode: true
      register: grub_cmdline_check_biosdevname
      changed_when: false

    - name: Insert param in grub config
      lineinfile:
        backrefs: yes
        path: /etc/default/grub
        state: present
        regexp: '^(GRUB_CMDLINE_LINUX=\".*)\"$'
        line: '\1 net.ifnames=0 biosdevname=0"'
      when: grub_cmdline_check.found == 0 and grub_cmdline_check_biosdevname.found == 0
      notify:
        - reconfigure grub
  tags:
    - configure_grub