---
users:
  - { name: "Alice", password: {{ Alice.password }}, comment: "Alice@example.com", home: "/home/Alice" }
  - { name: "Bob", password: {{ Bob.password }}, comment: "Bob@example.com", home: "/home/Bob" }
  - { name: "Carol", password: {{ Carol.password }}, comment: "Carol@example.com", home: "/home/Carol" }