---
- name: Install, enable and configure vsftpd
  block:
    - name: Install vsftpd
      yum: name=vsftpd state=latest

    - name: Enable vsftpd service
      service: name=vsftpd.service state=started

    - name: Enable ftp port
      firewalld: service=ftp state=enabled permanent=yes
      notify:
        - reload firewalld

    - name: Create directory
      file: path="{{ dir_path }}" state=directory mode=0777 owner=root

    - name: Editing vsftpd.conf file
      template: src="vsftpd.conf.j2" dest="{{ config_path }}" mode=0644 owner=root
      notify:
        - reload vsftpd

    - name: Set selinux boolean param
      seboolean: name=ftpd_anon_write state=yes persistent=yes ignore_selinux_state=yes
      #with_dict: "{{ vsftpd_seboolean }}"

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'