---
- name: Install, enable and configure vsftpd
  block:
    - name: Install vsftpd
      yum: name=vsftpd state=latest

    - name: Enable vsftpd service
      service: name=vsftpd.service state=started enabled=yes

    - name: Enable ftp port
      firewalld: service=ftp state=enabled permanent=yes
      notify:
        - reload firewalld

    - name: Create directory {{ dir_path }}
      file: path="{{ dir_path }}" state=directory mode=0777 owner=root

    - name: Editing vsftpd.conf file
      template: src="vsftpd.conf.j2" dest="{{ config_path }}" mode=0644 owner=root
      notify:
        - reload vsftpd
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  tags:
    - install_vsftpd

- name: Configure SELinux properties
  block:
    - name: Install requirements are needed on the host
      yum: name={{ item }} state=latest
      loop: ['python3-libselinux', 'python3-libsemanage', 'policycoreutils-python-utils']

    - name: Setting SELinux booleans
      seboolean:
        name: "{{ item.key }}"
        state: "{{ item.value }}"
        ignore_selinux_state: 'yes'
        persistent: 'yes'
      with_dict: "{{ vsftpd_seboolean }}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  tags:
    - install_sebool